# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tipos', models.CharField(choices=[('COMIDA', 'Alimentacao'), ('EDUCA', 'Educacao'), ('ACESS', 'Acessorios'), ('HIGI', 'Higienizacao'), ('ANTI', 'Antiparazitas')], max_length=6)),
            ],
        ),
    ]
